<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Delete_Layer</name>
   <tag></tag>
   <elementGuidId>aed83184-e914-403b-b65c-4cf91e098c3b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MzExMDcxNTAsImV4cCI6MTUzMTEyNTE1MCwiZGF0YSI6eyJ1c2VyX2lkIjoiNDY4MTYyMDgzNDE3Mzg1MzY0NCIsImRpdmlzaW9uX2lkIjoiNDY4MTYyMDgzMjU2MzIzOTg1MyIsImxhYmVsX2lkcyI6W10sImRpdmlzaW9uX2xhYmVsX2lkcyI6W10sImNvbXBhbnlfaWQiOiI0NjgxNjIwODMxNjc0MDQ2NDcxIiwicGxhdGZvcm0iOiJkYXNoYm9hcmQiLCJ1c2VyX2xldmVsX2NvZGVfbmFtZSI6ImFkbWluIn19.d2zLsTmHzNIYS-Jo99H-o04fe-_PBvgUO5WaNLo-YTA</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>DELETE</restRequestMethod>
   <restUrl>https://quackapipolda-staging.azurewebsites.net/v1/companies/4681620831674046471/layers/4707277326843390270</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceFunction></soapServiceFunction>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
