<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Get_Latest_Version</name>
   <tag></tag>
   <elementGuidId>ef9ab73d-dfc3-4095-8579-24638005e136</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MzExMjU2OTAsImV4cCI6MTUzMTE0MzY5MCwiZGF0YSI6eyJ1c2VyX2lkIjoiNDY4MTYyMDgzNDE3Mzg1MzY0NCIsImRpdmlzaW9uX2lkIjoiNDY4MTYyMDgzMjU2MzIzOTg1MyIsImxhYmVsX2lkcyI6W10sImRpdmlzaW9uX2xhYmVsX2lkcyI6W10sImNvbXBhbnlfaWQiOiI0NjgxNjIwODMxNjc0MDQ2NDcxIiwicGxhdGZvcm0iOiJkYXNoYm9hcmQiLCJ1c2VyX2xldmVsX2NvZGVfbmFtZSI6ImFkbWluIn19.sluAAe2QfuzujGVSbZbxTajsFJr4zG_byPgs0lIfyds</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>https://quackapipolda-staging.azurewebsites.net/latest_version</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceFunction></soapServiceFunction>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
